export const steemTip = 'Tradeable tokens that may be transferred anywhere at anytime. Steem can be converted to Steem Power in a process called powering up.'
export const dollarTip = 'Tokens worth about $1.00 of STEEM, currently collecting 10% APR.'
export const powerTip = 'Influence tokens which give you more control over post payouts and allow you to earn on curation rewards.'
export const valueTip = 'The estimated value is based on a 7 day average value of Steem in US Dollars.'
export const powerTip2 = 'Steem Power is non-transferrable and will require 2 years and 104 payments to convert back to Steem.'
export const powerTip3 = 'Converted Steem Power can be sent to yourself or someone else but can not transfer again without converting back to Steem.'
