#!/bin/bash
/usr/bin/wait-for-it.sh mysql:3306
/usr/bin/wait-for-it.sh steemitcom:8090
cd /steemit.com/db
sequelize db:migrate
cd /steemit.com
npm i
npm i react@15.3.1
npm cache clean
npm run build
npm run prod
