const 	APP_NAME = 'Golos', // 'Steemit',
		APP_URL = 'golos.io', // 'steemit.com'
		OWNERSHIP_TOKEN = 'Golos', // 'STEEM'
		INVEST_TOKEN = 'Сила Голоса', // 'STEEM POWER'
		INVEST_TOKEN_SHORT = 'MG', // 'SP'
		DEBT_TOKEN = 'Golos Backed Gold', // 'STEEM DOLLAR'
		DEBT_TOKEN_SHORT = 'GBG', // 'SD'
		CURRENCY_SIGN = '₽', // '$'
		SEGMENT_ANALYTICS_KEY = 'tNUbmBxX8o1OAWIkFRGMTMpXe6BfNLBb'

export {
	APP_NAME,
	APP_URL,
	OWNERSHIP_TOKEN,
	INVEST_TOKEN,
	INVEST_TOKEN_SHORT,
	DEBT_TOKEN,
	DEBT_TOKEN_SHORT,
	CURRENCY_SIGN,
	SEGMENT_ANALYTICS_KEY
}
