export const FAVORITES_LOAD = 'favorites/LOAD';
export const FAVORITES_TOGGLE = 'favorites/TOGGLE';
export const FAVORITES_LOAD_NEXT_PAGE = 'favorites/LOAD_NEXT_PAGE';
export const FAVORITES_LOADING_STARTED = 'favorites/LOADING_STARTED';
export const FAVORITES_SET_DATA = 'favorites/SET_DATA';
export const FAVORITES_COMPLETE_PAGE_LOADING = 'favorites/COMPLETE_PAGE_LOADING';
export const FAVORITES_SET_PAGE_LOADING = 'favorites/SET_PAGE_LOADING';

export const FAVORITES_REQUEST = 'favorites/REQUEST';
export const FAVORITES_REQUEST_SUCCESS = 'favorites/REQUEST_SUCCESS';
export const FAVORITES_REQUEST_ERROR = 'favorites/REQUEST_ERROR';

export const FAVORITES_TOGGLE_REQUEST = 'favorites/TOGGLE_REQUEST';
export const FAVORITES_TOGGLE_REQUEST_SUCCESS = 'favorites/TOGGLE_REQUEST_SUCCESS';
export const FAVORITES_TOGGLE_REQUEST_ERROR = 'favorites/TOGGLE_REQUEST_ERROR';
