export const GATE_CONNECT = 'gate/CONNECT';
export const GATE_CONNECT_SUCCESS = 'gate/CONNECT_SUCCESS';
export const GATE_CONNECT_ERROR = 'gate/CONNECT_ERROR';
export const GATE_AUTHORIZED = 'gate/GATE_READY';
export const GATE_DISCONNECT = 'gate/DISCONNECT';

export const GATE_SEND_MESSAGE = 'gate/SEND_MESSAGE';

export const GATE_NOTIFY_GET_HISTORY = 'gate/NOTIFY_GET_HISTORY';
export const GATE_NOTIFY_GET_HISTORY_SUCCESS = 'gate/NOTIFY_GET_HISTORY_SUCCESS';
export const GATE_NOTIFY_GET_HISTORY_ERROR = 'gate/NOTIFY_GET_HISTORY_ERROR';