export const NOTIFICATION_GET_HISTORY = 'notifications/GET_HISTORY';
export const NOTIFICATION_GET_HISTORY_SUCCESS = 'notifications/GET_HISTORY_SUCCESS';
export const NOTIFICATION_GET_HISTORY_ERROR = 'notifications/GET_HISTORY_ERROR';