export const RATES_GET_HISTORICAL = 'rates/GET_HISTORICAL';
export const RATES_GET_HISTORICAL_REQUEST = 'rates/GET_HISTORICAL_REQUEST';
export const RATES_GET_HISTORICAL_SUCCESS = 'rates/GET_HISTORICAL_SUCCESS';
export const RATES_GET_HISTORICAL_ERROR = 'rates/GET_HISTORICAL_ERROR';

export const RATES_GET_ACTUAL = 'rates/GET_ACTUAL';
export const RATES_GET_ACTUAL_REQUEST = 'rates/GET_ACTUAL_REQUEST';
export const RATES_GET_ACTUAL_SUCCESS = 'rates/GET_ACTUAL_SUCCESS';
export const RATES_GET_ACTUAL_ERROR = 'rates/GET_ACTUAL_ERROR';
