export default `
/children/@carlidos/why-it-s-important-to-teach-your-child-gratitude
/curation/@carlidos/lead-by-better-borrowing-3-content-curation-tips-100-of-steem-dollars-will-be-donated-to-curie
/compliment/@carlidos/you-get-complimented-on-and-you-cower-down-why
/motivation/@carlidos/the-power-that-moves-the-world
/project-positivity/@carlidos/the-wonder-of-mother-earth-project-positivity
/children/@carlidos/impossible-to-get-anything-done-with-a-preschooler-at-home
/steemit/@carlidos/internet-censorship-and-surveillance
/life/@carlidos/how-your-child-develops-emotionally-through-play-focuses-on-my-son
/kyoto/@carlidos/two-days-in-kyoto-japan
/psych101/@psych101/psych-101-moving-through-and-recovering-from-social-anxiety
/crowdfunding/@carlidos/the-basics-of-crowdfunding
/psychology/@carlidos/psych-101-classic-schools-of-thoughts-in-psychology
/psychology/@carlidos/the-makings-of-schizophrenia-part-1
/psychology/@carlidos/psych-101-beginner-operant-condition
/luciddreaming/@carlidos/6wisjx-how-to-interpret-your-own-dreams
/life/@carlidos/regain-control-of-your-time-and-finally-get-things-done
/psych101/@psych101/psych-101-show-your-appreciation-to-those-close-to-you-while-you-still-can
/life/@carlidos/psych-101-the-temptation-to-project-in-cyberspace-psych-101-the-trap-of-projection-in-cyberspace
/life/@carlidos/psych-101-support-groups-and-the-risks-of-imitation
/life/@carlidos/the-pitfalls-of-dating-with-a-big-age-difference-psychology
/life/@carlidos/psych-101-how-to-induce-a-lucid-dream-psych-101-the-memory-palace
/psychology/@carlidos/psych-101-beginner-classical-conditioning-psych-101-intermediate-classical-conditioning
/sex/@carlidos/honoring-your-sexual-needs-and-boundaries-within-a-relationship
/life/@carlidos/the-power-of-trusting-yourself
/psych/@carlidos/psych-101-how-psychology-shapes-our-world
/love/@carlidos/is-love-without-attachment-possible
/food/@outchemy/5-top-countries-you-need-to-visit-if-you-are-a-chocolate-addict
/travel/@outchemy/broken-relationships-the-museum-of-zagreb-that-celebrates-heartache
/travel/@outchemy/get-rid-of-the-toxins-see-these-amazing-detox-vacations
/photography/@maxmalini/the-dark-hedges
/creation/@andysyuhada/toys-creation-own-photography
/photography/@andysyuhada/animals-photography
/photography/@andysyuhada/flies-and-locusts-aceh
/photography/@andysyuhada/how-to-make-toys-photography
/photography/@andysyuhada/life-photography-toys
/photography/@andysyuhada/photographing-birds-in-a-tree-relaxing
/photography/@andysyuhada/toys-photography-life-toys
/photography/@andysyuhada/toys-photography-very-funny-was-dancing-and-singing
/photography/@andysyuhada/tutorial-photography-pengujian-kamera
/photography/@elvinanurhaliza/butterfly-photography
/photography/@elvinanurhaliza/finepix-s4800-reptiles-etc
/photography/@elvinanurhaliza/photography-flowers-finepix-s4800
/photography/@elvinanurhaliza/photohraphy-dewy-flowers
/photography/@elvinanurhaliza/spider-finepix-s4800-reptiles-etc
/entertainment/@seanfrederic/feature-film-loco-i-m-a-producer-on-starts-filming-soon
/cryptocurrency/@kriptonoob/palm-beach-confidential-report-cindicator-125
/crypto/@medicbtom/palm-beach-confidential-released-their-monthly-pick
/news/@vaerospace/fire-and-fury-pdf-direct-download-from-ipfs-a-great-giggle
/steemshorts/@mianusman/mianusman-contest-steemshort-1-illustration-short-story-and-even-shorter-illustration
/gaming/@braini/fifa-18-review-realistic-and-prettier-than-ever
/gaming/@braini/lost-sphear-review-charming-but-too-expensive
/gaming/@braini/bayonetta-switch-review-play-like-a-madman
/gaming/@braini/yakuza-6-the-song-of-life-review-on-fire
/gaming/@braini/assassin-s-creed-origins-curse-of-the-pharaohs-review-a-wonderful-history-lesson
/gaming/@braini/the-ultimate-cockpit-for-flight-simulation-games-all-requirements-for-choosing-the-virtual-airspace
/gaming/@braini/game-of-thrones-cluedo-review-murder-and-mystery-and-westeros
/gaming/@braini/sid-meier-s-civilization-6-rise-and-fall-review-more-dynamic
/gaming/@braini/immortal-redneck-review-a-classic-roguelike-shooter-in-egypt
/gaming/@braini/rad-rodgers-review-nice-dark-humor
/gaming/@braini/you-should-keep-an-eye-on-these-5-upcoming-rpgs
/gaming/@braini/crossing-souls-review-a-well-known-journey-into-the-past
/gaming/@braini/pokemon-crystal-review-still-a-masterpiece
/gaming/@braini/7-almost-perfect-games-the-best-of-the-best
/gaming/@braini/aegis-defenders-review-a-unique-mix-of-fun
/gaming/@braini/shu-review-feels-a-bit-like-a-bare-chicken
/gaming/@braini/nine-parchments-switch-review-unbelievably-unforgivable
/film/@braini/annabelle-creation-review-blu-ray-a-scary-prequel
/gaming/@braini/playstation-plus-game-deus-ex-mankind-divided-tips
/gaming/@braini/little-witch-academia-preview-magic-for-dummies
/gaming/@braini/bravo-team-preview-saving-the-lot-in-vr-together
/gaming/@braini/one-piece-world-seeker-preview-open-world-in-sight
/gaming/@braini/gear-club-unlimited-review-the-racing-game-for-the-switch
/gaming/@braini/monopoly-for-switch-almost-like-the-real-board-game
/gaming/@braini/destiny-2-curse-of-osiris-review-is-this-all
/gaming/@braini/lets-sing-2018-review-wrong-tone
/gaming/@braini/the-best-horror-games-of-2017-play-with-sweaty-hands
/forbes/@agcaapo/the-33-cheapest-places-to-travel-in-2018-forbes
/flstudio/@cracked-games/ltxziiz9
/music/@jneelocamacho/how-to-download-free-fl-studio-mobile
/downloadhd/@marvinlox/download-baaghi-2-2018-full-movie-in-720p-hd-dvdrip-filmywap
/baaghi/@hd-movie-watch/baaghi-2-2018-hindi-full-movie-download-hd-bluray-dvdrip-version
/watch/@herih511/baaghi-2-full-movie-hd
/movies/@mariarose4568/baaghi-2-hindi-full-movie-watch-online-2018-free-download-hd
/movie/@alisawells/baaghi-2-full-movie-in-1080-hd-dvdrip-bluerayrip-in-hindi
/action/@padmaavat/baaghi-2-hindi-2018-full-hd-movie-download
/action/@padmaavat/download-hd-baaghi-2-full-movie-online-watch
/watch/@mymunah21/watch-download-baaghi-2-baaghi-2-2018-full-movie-in-1080p-hd-dvdrip-bluerayrip
/baaghi2ktorrent/@gautampartapsoni/baaghi-2-baaghi-2-full-movie-download-720p-hdtv-bluray-hindi-torrent
/baaghi2torrent/@gautampartapsoni/baaghi-2-baaghi-2-hindi-full-movie-download-watch-online-720p-or-filmywap
/music/@therealtblgk/fl-studio-12-4-2-for-1-sbd
/music/@therealtblgk/fl-studio-12-4-2-digital-download-for-windows-first-3-to-comment-will-get-a-free-copy
/photography/@jimreitz/seattle-sky-view
/photography/@jimreitz/seattle-moonrise
/photography/@jimreitz/50-shades-of-purple
/photography/@jimreitz/wildebeest-silhouettes-at-sunrise-etosha-national-park-namibia
/photography/@jimreitz/sunset-stampede
/photography/@jimreitz/night-cave
/nature/@jimreitz/lone-ranch-beach-near-brookings-oregon
/colorchallenge/@jimreitz/hello-steemit-i-m-jim
/dtube/@derrick829/1r3fevhu
/technology/@taslimabegum/can-t-crack-fl-studio-12-5-on-windows-10
/story/@zahidzzs/step-into-the-darkness
/movie/@mariarose4568/pari-2018-full-movie-in-1080-hd-dvdrip-bluerayrip
/j/@nandinirana9218/abhiyude-kadha-anuvinteyum-2018-full-movie-online-in-hd
/telugumovie/@agroup85/rangasthalam-full-movie-download-720p-hd-telugu-yts-yify-filmywap
/dbooks/@tracytegan/mr-washington-chapter-10-chapter-ten
/dbooks/@tracytegan/mr-washington-chapter-9-chapter-nine
/dbooks/@tracytegan/mr-washington-chapter-8-chapter-eight
/dbooks/@tracytegan/mr-washington-chapter-7-chapter-seven
/dbooks/@tracytegan/mr-washington-chapter-6-chapter-six
/dbooks/@tracytegan/mr-washington-chapter-5-chapter-five
/dbooks/@tracytegan/mr-washington-chapter-4-chapter-four
/dbooks/@tracytegan/mr-washington-chapter-3-undefined
/dbooks/@tracytegan/mr-washington-chapter-2-
/dbooks/@tracytegan/mr-washington-chapter-1-chapter-one
/octoberfullmovie/@gautamsoni4k/october-2018-full-movie-download-online-free-watch-hd-print-bluray
/deadpool2/@watch-hd-movies/download-deadpool-2-2018-1080p-full-movie-online
/travel/@indiantraveller/how-i-traveled-around-sri-lanka-for-two-weeks-by-sammy
/kr/@jesusaddict/about-ico-r3security-token-offering
/children/@elizapfau/children-are-the-future-of-our-nations-they-will-correct-your-current-mistakes-in-future
/j/@kavyasheth3/tu-sooraj-main-saanjh-piyaji-17th-april-2018-full-episode-watch-online
`
    .trim()
    .split('\n');
