export default `
/carlidos/why-it-s-important-to-teach-your-child-gratitude
/carlidos/lead-by-better-borrowing-3-content-curation-tips-100-of-steem-dollars-will-be-donated-to-curie
/carlidos/you-get-complimented-on-and-you-cower-down-why
/carlidos/the-power-that-moves-the-world
/carlidos/the-wonder-of-mother-earth-project-positivity
/carlidos/impossible-to-get-anything-done-with-a-preschooler-at-home
/carlidos/internet-censorship-and-surveillance
/carlidos/how-your-child-develops-emotionally-through-play-focuses-on-my-son
/carlidos/two-days-in-kyoto-japan
/psych101/psych-101-moving-through-and-recovering-from-social-anxiety
/carlidos/the-basics-of-crowdfunding
/carlidos/psych-101-classic-schools-of-thoughts-in-psychology
/carlidos/the-makings-of-schizophrenia-part-1
/carlidos/psych-101-beginner-operant-condition
/carlidos/6wisjx-how-to-interpret-your-own-dreams
/carlidos/regain-control-of-your-time-and-finally-get-things-done
/psych101/psych-101-show-your-appreciation-to-those-close-to-you-while-you-still-can
/carlidos/psych-101-the-temptation-to-project-in-cyberspace-psych-101-the-trap-of-projection-in-cyberspace
/carlidos/psych-101-support-groups-and-the-risks-of-imitation
/carlidos/the-pitfalls-of-dating-with-a-big-age-difference-psychology
/carlidos/psych-101-how-to-induce-a-lucid-dream-psych-101-the-memory-palace
/carlidos/psych-101-beginner-classical-conditioning-psych-101-intermediate-classical-conditioning
/carlidos/honoring-your-sexual-needs-and-boundaries-within-a-relationship
/carlidos/the-power-of-trusting-yourself
/carlidos/psych-101-how-psychology-shapes-our-world
/carlidos/is-love-without-attachment-possible
/outchemy/5-top-countries-you-need-to-visit-if-you-are-a-chocolate-addict
/outchemy/broken-relationships-the-museum-of-zagreb-that-celebrates-heartache
/outchemy/get-rid-of-the-toxins-see-these-amazing-detox-vacations
/maxmalini/the-dark-hedges
/andysyuhada/toys-creation-own-photography
/andysyuhada/animals-photography
/andysyuhada/flies-and-locusts-aceh
/andysyuhada/how-to-make-toys-photography
/andysyuhada/life-photography-toys
/andysyuhada/photographing-birds-in-a-tree-relaxing
/andysyuhada/toys-photography-life-toys
/andysyuhada/toys-photography-very-funny-was-dancing-and-singing
/andysyuhada/tutorial-photography-pengujian-kamera
/elvinanurhaliza/butterfly-photography
/elvinanurhaliza/finepix-s4800-reptiles-etc
/elvinanurhaliza/photography-flowers-finepix-s4800
/elvinanurhaliza/photohraphy-dewy-flowers
/elvinanurhaliza/spider-finepix-s4800-reptiles-etc
/seanfrederic/feature-film-loco-i-m-a-producer-on-starts-filming-soon
`.trim().split('\n');
