module.exports = {
    get_transports: {
        id: 1,
        jsonrpc: '2.0',
        result: {
            email: {
                notification_types: [
                    'account_update',
                    'power_down',
                    'security_new_mobile_device',
                    'security_withdrawal',
                    'security_password_changed',
                    'receive',
                    'reward',
                    'send',
                    'post_reply',
                ],
                sub_data: 'test@example.com',
            },
            wwwpoll: {
                notification_types: null,
                sub_data: '',
            },
        },
    },
    saved_transports: {
        id: 1,
        jsonrpc: '2.0',
        result: {
            email: {
                notification_types: [
                    'account_update',
                    'power_down',
                    'security_new_mobile_device',
                    'security_withdrawal',
                    'security_password_changed',
                    'receive',
                    'reward',
                    'send',
                    'post_reply',
                ],
                sub_data: 'test@example.com',
            },
            wwwpoll: {
                notification_types: [
                    'account_update',
                    'power_down',
                    'security_new_mobile_device',
                    'security_withdrawal',
                    'security_password_changed',
                    'receive',
                    'reward',
                    'send',
                    'mention',
                    'feed',
                    'resteem',
                ],
                sub_data: '',
            },
        },
    },
    get_notifications: {
        jsonrpc: '2.0',
        id: 1,
        result: [
            {
                notify_id: 1,
                notify_type: 'account_update',
                created: '2017-10-27T01:31:29.382749',
                updated: '2017-10-27T01:31:29.382749',
                read: false,
                shown: false,
                username: 'theoretical',
                data: {
                    json_metadata: '',
                    account: 'theoretical',
                    memo_key:
                        'STM6FATHLohxTN8RWWkU9ZZwVywXo6MEDjHHui1jEBYkG2tTdvMYo',
                    posting: {
                        key_auths: [
                            [
                                'STM6FATHLohxTN8RWWkU9ZZwVywXo6MEDjHHui1jEBYkG2tTdvMYo',
                                1,
                            ],
                            [
                                'STM76EQNV2RTA6yF9TnBvGSV71mW7eW36MM7XQp24JxdoArTfKA76',
                                1,
                            ],
                        ],
                        account_auths: [],
                        weight_threshold: 1,
                    },
                },
            },
            {
                notify_id: 2,
                notify_type: 'comment_reply',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'steemit',
                data: {
                    title: 'Welcome to Steem Reply',
                    parent_permlink: 'firstpost-reply',
                    permlink: 'firstpost-reply-comment',
                    parent_author: 'steemit',
                    body: 'I agree!',
                    json_metadata: '',
                    author: 'steemit',
                },
            },
            {
                notify_id: 3,
                notify_type: 'feed',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'test_user',
                data: {},
            },
            {
                notify_id: 4,
                notify_type: 'follow',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'steemit',
                data: {
                    required_auths: [],
                    id: 'follow',
                    json:
                        '{"follower":"steemit","following":"steem","what":["posts"]}',
                    required_posting_auths: ['steemit'],
                },
            },
            {
                notify_id: 5,
                notify_type: 'mention',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'test_user',
                data: {
                    title: 'Welcome to Steem!',
                    parent_permlink: 'meta',
                    permlink: 'firstpost',
                    parent_author: 'steemit',
                    body:
                        'Steemit is a social media platform where anyone can earn STEEM points by posting, even @test_user.',
                    json_metadata: '',
                    author: 'steemit',
                },
            },
            {
                notify_id: 6,
                notify_type: 'post_reply',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'steemit',
                data: {
                    title: 'Welcome to Steem Reply',
                    parent_permlink: 'firstpost',
                    permlink: 'firstpost-reply',
                    parent_author: 'steemit',
                    body: 'Sounds great!',
                    json_metadata: '',
                    author: 'steemit',
                },
            },
            {
                notify_id: 7,
                notify_type: 'power_down',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'steemit',
                data: {
                    vesting_shares: '200000.000000 VESTS',
                    account: 'steemit',
                },
            },
            {
                notify_id: 8,
                notify_type: 'send',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'admin',
                data: {
                    amount: '833.000 STEEM',
                    from: 'admin',
                    to: 'steemit',
                    memo: '',
                },
            },
            {
                notify_id: 9,
                notify_type: 'receive',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'steemit',
                data: {
                    amount: '833.000 STEEM',
                    from: 'admin',
                    to: 'steemit',
                    memo: '',
                },
            },
            {
                notify_id: 10,
                notify_type: 'resteem',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'test_user',
                data: {},
            },
            {
                notify_id: 11,
                notify_type: 'reward',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'ivelina89',
                data: {
                    author: 'ivelina89',
                    permlink: 'friends-forever',
                    sbd_payout: '2.865 SBD',
                    steem_payout: '0.000 STEEM',
                    vesting_payout: '1365.457442 VESTS',
                },
            },
            {
                notify_id: 12,
                notify_type: 'vote',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'steemit78',
                data: {
                    voter: 'steemit78',
                    permlink: 'firstpost',
                    author: 'steemit',
                    weight: 10000,
                },
            },
        ],
    },
    // Only the last one is valid according to the json-schema.
    get_bad_notifications: {
        jsonrpc: '2.0',
        id: 1,
        result: [
            {
                notify_id: 1,
                bbbbbhnotify_type: 'account_update',
                created: '2017-10-27T01:31:29.382749',
                updated: '2017-10-27T01:31:29.382749',
                read: false,
                shown: false,
                username: 'theoretical',
                data: {
                    json_metadata: '',
                    account: 'theoretical',
                    memo_key:
                        'STM6FATHLohxTN8RWWkU9ZZwVywXo6MEDjHHui1jEBYkG2tTdvMYo',
                    posting: {
                        key_auths: [
                            [
                                'STM6FATHLohxTN8RWWkU9ZZwVywXo6MEDjHHui1jEBYkG2tTdvMYo',
                                1,
                            ],
                            [
                                'STM76EQNV2RTA6yF9TnBvGSV71mW7eW36MM7XQp24JxdoArTfKA76',
                                1,
                            ],
                        ],
                        account_auths: [],
                        weight_threshold: 1,
                    },
                },
            },
            {
                pfffnotify_id: 2,
                notify_type: 'comment_reply',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'steemit',
                data: {
                    title: 'Welcome to Steem Reply',
                    parent_permlink: 'firstpost-reply',
                    permlink: 'firstpost-reply-comment',
                    parent_author: 'steemit',
                    body: 'I agree!',
                    json_metadata: '',
                    author: 'steemit',
                },
            },
            {
                notify_id: 2666,
                notify_type: 'comment_reply',
                created: '2017-10-27T01:15:29.383842',
                updated: '2017-10-27T01:15:29.383842',
                read: false,
                shown: false,
                username: 'steemit',
                data: {
                    title: 'Welcome to Steem Reply',
                    parent_permlink: 'firstpost-reply',
                    permlink: 'firstpost-reply-comment',
                    parent_author: 'steemit',
                    body: 'I agree!',
                    json_metadata: '',
                    author: 'steemit',
                },
            },
        ],
    },
};
